### PR TITLE
Build a pkgdown site

### PR DESCRIPTION
**Pull request by stephlocke**

### CODE REVIEW

**Comment by stephlocke** [comment]
@thibautjombart I'm putting in a little extra for you around publishing and consolidating pkgdown sites onto your website. They'll be individually available eg reconhub.github.io/reportfactory via publishing the gh-pages as a site using github settings but with an additional command for each on the reconhub.github.io repo we can pull them into the main site e.g. repidemicsconsortium.org/reportfactory

**Comment by stephlocke** [comment]
Hey @thibautjombart I need you to run `travis::use_travis_deploy()` to make sure travis can do the deploy. 
```
> travis::use_travis_deploy()
✔ Setting active project to 'T:/reportfactory'
>  Authenticating to GitHub.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
√ Authentication successful.
>  Authenticating to GitHub.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
√ Authentication successful.
Error: Must have role admin to add deploy key to repo reconhub/reportfactory, not write
```

**Comment by thibautjombart** [comment]
Just added you as admin - let me know if that works.

**Comment by stephlocke** [comment]
Magic has happened 🎉 https://www.repidemicsconsortium.org/reportfactory

In the end, I actually used github actions for pkgdown because it was behaving super weirdly on travis and the response on some of the github issues about it was "travis is no longer supported" :(

**Comment by stephlocke** [comment]
To implement on other sites...

In terminal to make a blank gh-pages branch
```bash
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m 'Initial gh-pages commit'
git push origin gh-pages
git checkout master
```

Then in R to setup pkgdown and the github action
```r
usethis::use_pkgdown()
usethis::use_github_actions()
usethis::use_github_action("pkgdown")
```

**Pull request merged**
